### PR TITLE
Experimental branch

### PR DESCRIPTION
**Pull request by costashatz**
The experimental things are far from being compiled and working, but I think now they are safely marked as experimental == not working as they should be. I think we should merge now and create an issue (I think we already have one) to make the experimental (multi-objective) things compile and work as they should be.

I am using the full name **experimental** both in folder name and in namespace name and not *exp* for 2 reasons:

- We have **exp** as the name of the experiments folder and we do not want to be confusing things. We even have a gitignore rule to ignore *exp* folders. Also, sometimes the compiler confused the call to **std::exp** function with the namespace name **exp**.
- The experimental stuff will not be used regularly and so do not mind writing some more characters, so that everything is more clear.

Any thoughts?

### CODE REVIEW

**Comment by fedeallocati** [comment]
Looks good. Just 2 things.
- Maybe I remember wrong, but didn't we said to move the stop criterion "MaxPredictedValue" to experimental?
- Why always compile the experimental examples (``bld.recurse('experimental/')``)? Wouldn't it be better to include it conditionally on a cmd-line flag?

**Comment by costashatz** [comment]
> Maybe I remember wrong, but didn't we said to move the stop criterion "MaxPredictedValue" to experimental?

I do not remember. If so, I can do it.


> Why always compile the experimental examples (bld.recurse('experimental/'))? Wouldn't it be better to include it conditionally on a cmd-line flag?

We always compile them, but they have empty wscript. But you are right, it's better if we have a cmd-line argument.

**Comment by costashatz** [comment]
What should I do for **MaxPredictedValue**?

**Comment by costashatz** [comment]
> What should I do for MaxPredictedValue?

Any suggestions for this one?

**Comment by costashatz** [comment]
Should we merge then?

**Pull request merged**
