### PR TITLE
experimental kernel function: squared exp ARD with full covariance matrix

### PR DESCRIPTION
**Pull request by Aneoshun**
Experimental implementation of the general squared exp ARD kernel, which contains a full covariance matrix (see Rasmussem & Williams 2004, p. 106).
This allows the GP to find correlation among the dimensions and select the most relevant dimensions (like in Factor Analysis).

Note: with Params::SquaredExpARD::k()=0, this kernel is equivalent to the classic one.

### CODE REVIEW

**Comment by costashatz** [comment]
> Experimental implementation of the general squared exp ARD kernel, which contains a full covariance matrix (see Rasmussem & Williams 2004, p. 106).
> This allows the GP to find correlation among the dimensions and select the most relevant dimensions (like in Factor Analysis).
> 
> Note: with Params::SquaredExpARD::k()=0, this kernel is equivalent to the classic one.

- Is there any overhead in the implementation of the classic one and using this one with k=0?
- Could you make unit tests?

If there's no overhead and we can ensure that it works as it should, then we can replace the exiting kernel with this new one.

**Comment by costashatz** [comment]
@Aneoshun any remarks on my comments above?

**Comment by Aneoshun** [comment]
Sorry about that.
My only comment is “Yes, I will do it”
But I am quite busy right now, so I will do it as soon as possible.

**Comment by costashatz** [comment]
> Sorry about that.
> My only comment is “Yes, I will do it”
> But I am quite busy right now, so I will do it as soon as possible.

No prob..

**Comment by Aneoshun** [comment]
The overhead is negligible (instantiation and product of an empty (dim=0) matrice).
Therefore, I put the generalized version of the kernel directly in Limbo (not in experimental) and I added a test_kernel unit test. 

Any remark?

**Comment by costashatz** [comment]
> Any remark?

It seems **OK** to me..

**Comment by jbmouret** [comment]
Do we need to add something to the doc?

**Comment by Aneoshun** [comment]
I already changed the equations in the API doc. I don't know if we need to say more.

By the way, in this doc, we say: The parameters :math:`l_1^2, \dots, l_n^2, \alpha, \Lambda` are expected in this order in the parameter array.   
However, the l values are then passed through std::exp(), which can be misleading w.r.t the doc. 
Should we say that: The parameters :math:`ln(l_1^2), \dots, ln(l_n^2), \alpha, \Lambda` are expected in this order in the parameter array.   
Kind of complicated... 
We can also change the equation and add the exp inside.

**Comment by costashatz** [comment]
So:

- I should have fixed compilation issues
- Rename the SquaredExpARD kernel's parameters to match the naming conventions we have defined.

We should wait for the tests to pass before merging...

**Comment by costashatz** [comment]
I think that we should close this PR and create a new one that merges the `general_expARD_kernel` branch into the `chol_incremental` branch... What do you think?

**Comment by jbmouret** [comment]
Ok for me.

**Pull request closed without merging**
