### PR TITLE
Stats improvements

### PR DESCRIPTION
**Pull request by fedeallocati**
Many improvements to stats:
- Added lots of new stats
- Added header comment specifying the column names
- Stats Samples and Observations output the initial samples/observations (with the iteration set to -1)
- Added a new iteration counter, for the total amount of iterations (useful when the optimizer is called repeated times with reset set to false). The previous `_iteration` variable got renamed to `_current_iteration` and resets each time the optimizer is called. The new variable is called `_total_iterations` and is restarted only when the optimizer is called with `reset = true`

### CODE REVIEW

**Comment by fedeallocati** [comment]
Extensive tests compile

**Comment by fedeallocati** [comment]
Extensive tests run withour errors

**Comment by fedeallocati** [comment]
Forgot to mention another modification:
* Changed the parameter `dump_period` to a boolean `stats_enabled`

**Comment by costashatz** [comment]
I think this PR is good!

**I approve**

**Comment by jbmouret** [comment]
**OK for me**

-- JBM (from phone)

**Pull request merged**
