### PR TITLE
Libcmaes

### PR DESCRIPTION
**Pull request by jbmouret**
First version (old CMA-ES not removed yet).

What do you think?

### CODE REVIEW

**Comment by costashatz** [comment]
With a first quick look, it looks okay.

Which library are you using? This [one](https://github.com/beniz/libcmaes) suggested by @fedeallocati in #48 ?

**Comment by jbmouret** [comment]
On 12 Dec 2015, at 20:07, Konstantinos Chatzilygeroudis <notifications@github.com> wrote:

> With a first quick look, it looks okay.
> 
> Which library are you using? This one suggested by @fedeallocati in #48 ?

Yes, this one. I am not 100% convinced by the design, but it has a few algorithms that are more recent.

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
Why you put 1.005 as upper bound? you tried it? with it, I'm getting a point of value 1.0049999999999999, which shouldn't be allowed. If I switch it to 1.0, it works good.

**Comment by costashatz** [comment]
> Why you put 1.005 as upper bound? you tried it? with it, I'm getting a point of value 1.0049999999999999, which shouldn't be allowed. If I switch it to 1.0, it works good.

I think most probably he used the same values we had before.

**Comment by jbmouret** [comment]
Yes, it was inspired by your magic Constant...

**Comment by fedeallocati** [comment]
Ok, it seems that with this cmaes, it can be removed

**Comment by jbmouret** [comment]
should we merge?

**Comment by costashatz** [comment]
> should we merge?

I notice some problems before merging:

- Conflicts (I am solving them now)
- I tried compiling it without libcmaes and it fails
- We haven't removed the previous cmaes code

I am focusing on the 1st and the 3rd. Would you like to do the second one?

**Comment by jbmouret** [comment]
OK. I'm doing it.

**Comment by costashatz** [comment]
> OK. I'm doing it.

Maybe we should also handle the case we were talking in the meeting: check if we have licmaes for the default it bobase, then NLOpt . If none, then fail an assertion or something.

**Comment by fedeallocati** [comment]
If there is no NLOpt and no libcmaes, we could default to the Grid Search, that surely won't perform good, but it still allows the library to compile without prerequisites

**Comment by costashatz** [comment]
> If there is no NLOpt and no libcmaes, we could default to the Grid Search, that surely won't perform good, but it still allows the library to compile without prerequisites

I am OK with this.

**Comment by costashatz** [comment]
I removed previous cmaes version, but check if I forgot something. Extensive tests compile.

**Comment by jbmouret** [comment]
This should compile without libcmaes now. Does someone want to check?

**Comment by costashatz** [comment]
I will check in a minute.

**Comment by costashatz** [comment]
It's compiling, but extensive tests are not!

**Comment by jbmouret** [comment]
Oops. They should now.

**Comment by costashatz** [comment]
They are compiling! Should we merge? **OK for me**

**Comment by jbmouret** [comment]
@fedeallocati ?

**Comment by fedeallocati** [comment]
** Ok for me **

**Pull request merged**
