### PR TITLE
Fix for boptimizer inheritance bug

### PR DESCRIPTION
**Pull request by costashatz**
Fix for #81 .. It is a little hacky, but it will save us from many unforeseen traps.. I also enabled the `boptimizer` test in the test routines...

### CODE REVIEW

**Comment by jbmouret** [comment]
Looks good to me.

**Comment by costashatz** [comment]
> Looks good to me.

I am fixing the `boptimizer` test to be able to pass...

**Comment by costashatz** [comment]
Should I **merge**?

**Comment by jbmouret** [comment]
Yes!

**Pull request merged**
