### PR TITLE
Removed ObsType

### PR DESCRIPTION
**Pull request by costashatz**
Removed unused ObsType.

### CODE REVIEW

**Comment by fedeallocati** [comment]
Still need to be removed from: GP, GPAuto, GPAutoMean, all of the Mean Functions, and the obs_multi_auto_mean example

**Comment by costashatz** [comment]
Should be OK.

**Comment by fedeallocati** [comment]
Still missing in the Mean functions

**Comment by fedeallocati** [comment]
**I approve now**

**Comment by jbmouret** [comment]
**Approved**

**Pull request merged**
