### PR TITLE
Extract param

### PR DESCRIPTION
**Pull request by jbmouret**
A new python tool that can:

- write the parameters used in a cpp files in a readable format, including the inherited defaults
- write the defaults parameters for limbo, to be included in the documentation

We could run this tool after the compilation of each cpp file that contains some parameters (some meta-data for the experiment).

**This still needs some polishing before being ready for merging** but you might want to have a look at it.

### CODE REVIEW

**Comment by costashatz** [comment]
@jbmouret I searched a little bit on what we discussed: how to execute the script after every compilation, but it is not as easy as it seemed at first. The easiest way would be that each user could create a target for running the script in his experiments and we could provide a template..

**Comment by jbmouret** [comment]
Maybe we could just add this for every *.cpp that contains params in the
--exp that is compiled ? that would be basic, standard Python code.

**Comment by costashatz** [comment]
> Maybe we could just add this for every *.cpp that contains params in the
> --exp that is compiled ? that would be basic, standard Python code.

OK. I will do it..

**Comment by jbmouret** [comment]
It's up to you but I think I can do it.

**Comment by costashatz** [comment]
@jbmouret I will do it. I have another question: What happens if we have several parameter declarations with `ifdef`? Like the following:

```cpp
#ifdef USE_ONE
BO_PARAM(double, test_param, 0.1);
#else
BO_PARAM(double, test_param, 0.2);
#endif
```

What will then happen?

**Comment by jbmouret** [comment]
For now we will take the last one, which is not what we want. I suppose we
should parse this as well and report the variants.

**Comment by costashatz** [comment]
> For now we will take the last one, which is not what we want. I suppose we
> should parse this as well and report the variants.

So, I should check in more detail how to do it properly with waf. For the moment, I will just implement a simple script for what we said before and we should create an issue about doing it properly.

**Comment by costashatz** [comment]
@jbmouret It should do for the moment...

**Comment by jbmouret** [comment]
I think we should call the script via a function call  and not call Python from Python via a subprocess...

**Comment by costashatz** [comment]
@jbmouret It should be okay now...

**Comment by costashatz** [comment]
I think that we should merge.. I opened an issue about the variant thing, see #110 ...

**Comment by costashatz** [comment]
It seems **OK** to me. I, also, *tested it in a simple experiment and it seems to work*.. **Let's merge...**

**Comment by costashatz** [comment]
Should we merge?

**Comment by jbmouret** [comment]
We merge but we still need to add the option to dump all the defaults (for the documentation).

**Pull request merged**
