### PR TITLE
clean the random generation API

### PR DESCRIPTION
**Pull request by jbmouret**
- A few shortcuts to make it easy to generate double numbers in (min, max).
- Remove the old rand() API (not thread safe, designed for sferes)

### CODE REVIEW

**Comment by jbmouret** [comment]
I did not update random_sampling_grid (which needs a random generation of int, I suppose?), but I think we should. Who did write this? I do not want to break it.

**Comment by jbmouret** [comment]
(still working on it, not ready)

**Comment by jbmouret** [comment]
@fedeallocati What do you think of the initialisation in model::gp::* ? it seems to be in [0, -2]... is it used? should we remove it?

**Comment by fedeallocati** [comment]
For me it seems completly like an unnoticed mistake, so I think we should remove it

**Comment by jbmouret** [comment]
@fedeallocati do we still call these methods?

**Comment by fedeallocati** [comment]
In theory they should still be called by the optimizers, until we fix and
merge the new optimization API

**Comment by jbmouret** [comment]
@fedeallocati the extensive tests do not compile, but I think you already fix this bug in another branch. What do you think?

**Comment by fedeallocati** [comment]
Yeah. I think this branch is **OK**

**Comment by costashatz** [comment]
When trying to compile the extensive tests I am getting the following error:

```
/combinations_8.cpp:125:18: error: ‘NLOptNoGrad’ in namespace ‘limbo::opt’ does not name a template type
```

**Comment by fedeallocati** [comment]
I think you should check first the new optimization api PR, and see if you
can discover what's the bug, because I believe it fixes this issue.

2016-01-08 13:00 GMT+01:00 Konstantinos Chatzilygeroudis <
notifications@github.com>:

**Comment by costashatz** [comment]
> I think you should check first the new optimization api PR, and see if you
> can discover what's the bug, because I believe it fixes this issue.

But in the new optimization api PR the extensive tests compile, but do not run. In this case, they do not even compile.

I am checking the other PR now.

**Comment by fedeallocati** [comment]
Yes, because I fixed the compilation in one of the commits

2016-01-08 13:09 GMT+01:00 Konstantinos Chatzilygeroudis <
notifications@github.com>:

**Comment by costashatz** [comment]
> Yes, because I fixed the compilation in one of the commits

OK. I will check!

**Comment by costashatz** [comment]
This seems ok. @jbmouret check that I didn't alter anything of what you wanted when merging with gp_multi.

**Comment by jbmouret** [comment]
That looks OK for me.

**Comment by costashatz** [comment]
It's **ok** for me too!

**Comment by fedeallocati** [comment]
Also **ok** for me

**Pull request merged**
