### PR TITLE
New optimization API

### PR DESCRIPTION
**Pull request by jbmouret**
This is the first version with a nicer API for optimization sub-algorithms. Some tests in the optimization of the likelihood do not pass. **This is not ready to be merged**. I suspect this is because I changed the initialization but I am not sure to understand how this is supposed to work. @fedeallocati ?

In addition, we should do a regression test and compare to bayesopt. @fedeallocati ?

Now (from test_optimizers.cpp):
```C++

// test with a standard function
int monodim_calls = 0;
opt::eval_t acqui_mono(const Eigen::VectorXd& v, bool eval_grad)
{
    assert(!eval_grad);
    monodim_calls++;
    return opt::no_grad(3 * v(0) + 5);
}
// ...
  Eigen::VectorXd best_point = optimizer(acqui_mono, Eigen::VectorXd::Constant(1, 0.5), true);
```

Before (gp_multi):
```C++

struct FakeAcquiMono {
    size_t dim_in() const { return 1; }

    double operator()(const Eigen::VectorXd& v) const
    {
        monodim_calls++;
        return 3 * v(0) + 5;
    }
};
template <typename Functor>
struct FunctorOptimization {
public:
    FunctorOptimization(const Functor& f, const Eigen::VectorXd& init) : _f(f), _init(init) {}

    double utility(const Eigen::VectorXd& params) const
    {
        return _f(params);
    }

    size_t param_size() const
    {
        return _f.dim_in();
    }

    const Eigen::VectorXd& init() const
    {
        return _init;
    }

protected:
    const Functor& _f;
    Eigen::VectorXd _init;
};


template <typename Functor>
FunctorOptimization<Functor> make_functor_optimization(const Functor& f)
{
    return FunctorOptimization<Functor>(f, Eigen::VectorXd::Constant(f.dim_in(), 0.5));
}

//...
        Eigen::VectorXd best_point = optimizer(make_functor_optimization(f), true);
//...

### CODE REVIEW

**Comment by costashatz** [comment]
`#include <limbo/opt/optimizer.hpp>`

Where is this file? I cannot compile it without it.

**Comment by jbmouret** [comment]
merge? @fedeallocati  @costashatz ?

**Comment by costashatz** [comment]
**OK for me**

**Comment by fedeallocati** [comment]
Have anyone compiled extensive tests?

**Comment by jbmouret** [comment]
Not yet. I am working on it.

**Comment by costashatz** [comment]
We should also fix the conflicts.

**Comment by jbmouret** [comment]
Extensive tests should build now.

**Comment by fedeallocati** [comment]
Extensive tests doesn't compile, but it's not the fault of this branch. I will make the fixes. One of the problems is that NLOptGrad/NoGrad don't provide a default algorithm, and in the template generation we are not setting it (because the other optimizers don't have additional template parameters). 
I can add the parameter to the template generation, but was wondering if we should provide default nlopt algorithms (probably DIRECT for NoGrad and maybe LBFGS for grad?). What do you think?

**Comment by jbmouret** [comment]
On 22 Dec 2015, at 12:51, Federico Allocati <notifications@github.com> wrote:

> Extensive tests doesn't compile, but it's not the fault of this branch. I will make the fixes. One of the problems is that NLOptGrad/NoGrad don't provide a default algorithm, and in the template generation we are not setting it (because the other optimizers don't have additional template parameters). 
> I can add the parameter to the template generation, but was wondering if we should provide default nlopt algorithms (probably DIRECT for NoGrad and maybe LBFGS for grad?). What do you think?

This should be OK.

regards,
� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
Seems good to me too to provide defaults.

**Comment by fedeallocati** [comment]
I did some fixes and managed to get the tests to compile, but then some of them throw different runtime errors, for example:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
```
combinations_88: /usr/include/eigen3/Eigen/src/Core/CwiseBinaryOp.h:131: Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::CwiseBinaryOp(const Lhs &, const Rhs &, const BinaryOp &) [with BinaryOp = Eigen::internal::scalar_difference_op<double>, Lhs = const Eigen::Matrix<double, -1, 1, 0, -1, 1>, Rhs = const Eigen::Matrix<double, -1, 1, 0, -1, 1>]: Assertion `aLhs.rows() == aRhs.rows() && aLhs.cols() == aRhs.cols()' failed
```
```
combinations_648: /home/fallocat/limbo/src/limbo/kernel/squared_exp_ard.hpp:47: double limbo::kernel::SquaredExpARD<Params>::operator()(const Eigen::Matrix<double, -1, 1, 0, -1, 1> &, const Eigen::Matrix<double, -1, 1, 0, -1, 1> &) const [with Params = Params]: Assertion `x1.size() == _ell.size()' failed.
```

I have no idea what's going on, maybe the fix in commit 1f45abc333c7e7ac24cf2899cbb500615994edc1 made it compile, but broke the execution.

**Comment by costashatz** [comment]
Extensive tests build and run successfully now!

**Comment by jbmouret** [comment]
Thanks!

On 13 Jan 2016, at 16:06, Konstantinos Chatzilygeroudis <notifications@github.com> wrote:

> Extensive tests build and run successfully now!
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
Should we merge?

**Pull request merged**
