### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by jbmouret**

### CODE REVIEW

**Comment by Aneoshun** [comment]
In addition to the "Scientific articles that use Limbo" do you want to add a section named "Research projects that use Limbo"? In this one we can add the Research project I am working on, alongside with Resibots.

**Comment by costashatz** [comment]
> In addition to the "Scientific articles that use Limbo" do you want to add a section named "Research projects that use Limbo"? In this one we can add the Research project I am working on, alongside with Resibots.

I find it a good idea...

**Comment by jbmouret** [comment]
Good idea

**Comment by Aneoshun** [comment]
alright, I will do it.

**Comment by costashatz** [comment]
Shoule we **merge**?

**Comment by costashatz** [comment]
**Merging...**

**Pull request merged**
