### PR TITLE
Adding waf create option

### PR DESCRIPTION
**Pull request by bpapaspyros**

### CODE REVIEW

**Comment by bpapaspyros** [comment]
Not sure that hardcoding the basic example is the best way to do this, what do you think ?

**Comment by fedeallocati** [comment]
Great job! The code looks good to me.
I have two remarks:
- The **noise** parameter is set to 0. I think this is not good for numerical stability. Quoting [BayesOpt's documentation](http://rmcantin.bitbucket.org/html/usemanual.html#basicparams): *For simulations and deterministic functions, it should be close to 0. However, to avoid numerical instability due to model inaccuracies, make it always greater than 0. For example, between 1e-10 and 1e-14.*
- I agree that it is good to have default parameters for everything, but I think that if we want more people to use, we should also add parameters in waf create to control them. Then, people doesn't even need to know about the Params struct and whatnot, they just code their objective functions.

**Comment by bpapaspyros** [comment]
> The noise parameter is set to 0. I think this is not good for numerical stability. Quoting BayesOpt's documentation: For simulations and deterministic functions, it should be close to 0. However, to avoid numerical instability due to model inaccuracies, make it always greater than 0. For example, between 1e-10 and 1e-14.

Makes sense, fixed it for the tutorials.

> I agree that it is good to have default parameters for everything, but I think that if we want more people to use, we should also add parameters in waf create to control them. Then, people doesn't even need to know about the Params struct and whatnot, they just code their objective functions.

I am not sure I will have enough time to do this soon, but I definitely agree, therefore, I propose we merge the changes up until this point and leave the branch open so that I can work on it in the future.

**Comment by costashatz** [comment]
> I am not sure I will have enough time to do this soon, but I definitely agree, therefore, I propose we merge the changes up until this point and leave the branch open so that I can work on it in the future.

I agree with @bpapaspyros.

Once the ci passes and someone tests it, I am **OK** with it..

**Comment by fedeallocati** [comment]
I think I may be able to put 1 or 2 hours of work on this this week, so if
you want, lets wait for that to merge.

**Comment by bpapaspyros** [comment]
> I think I may be able to put 1 or 2 hours of work on this this week, so if
> you want, lets wait for that to merge.

I'm OK with that, we should keep in mind that the travis.yml has a fix for the CI and clang+libcmaes though (we could update it separately and keep this branch until everything is completed with the waf)

**Comment by costashatz** [comment]
@fedeallocati do you have any progress on this one? We should hurry up to merge so that the travis tests pass on the other PRs too.

**Comment by fedeallocati** [comment]
@costashatz not yet. Weekend is coming and this is in the top of my To Do Heap :P

**Comment by fedeallocati** [comment]
I've got a question. As of know, the code is copying the **basic_example.cpp** from the tutorials folder. This example doesn't use all of the default values (from the `defaults` namespace), for example for the bo noise parameter. Now, if a cmd line arg for the bo_noise is supplied, the value is set to the value. But if there is no param, should I put the value from **basic_example.cpp** (1e-10 for noise), or just leave the struct empty (inheriting from `defaults` a value of 1e-6)?
The same question applies for other parameters, like stats_enables, number of initial samples or max iterations.

**Comment by bpapaspyros** [comment]
In my opinion, for some values maybe it makes sense to just get the defaults and not confuse the user. However, for values like max_iterations even if the basic example is using the default, I think we should be setting it explicitly so that if someone is not very familiar with limbo he wouldn't have to search for the defaults to "play" around. Having said that, we could also put a link to the documentation in the generated experiment (we should assume that not everyone has read about the defaults in the documentation)

**Comment by fedeallocati** [comment]
Ok, then we should decide what we do for each parameter. Here is the list of parameters that I have taken from the example to extract to parameters:
- bayes_opt_boptimizer noise (default is 1e-6, in the example it is set explicitly to 1e-10)
- bayes_opt_bobase stats_enabled (default is true, in the example it is set explicitly to true)
- init_randomsampling samples (default is 10, in the example it is set explicitly to 10)
- stop_maxiterations iterations (default is 190, in the example it is set explicitly to 40)

Also, we should decide a convention por the cmd line arguments name. One option is to put the same as the parameter struct name with the parameter name appended at the end like: bayes_opt_boptimizer_noise, Another option is to simplify the names arbitrarily, like bo_noise, or even just noise.

I would like to here what everybody thinks about this @jbmouret @costashatz @Aneoshun.

**Comment by fedeallocati** [comment]
I just finished this, only the naming conventions (and any feedback/comment) is missing.

**Comment by bpapaspyros** [comment]
Seems **OK** to me. We should consider merging soon. (We can change the naming convetions in the future if necessary, though it looks intuitive enough and good to me). Did anyone else check it ?

**Comment by costashatz** [comment]
> Did anyone else check it ?

I didn't but I trust you and Federico.

**Let's merge**!

**Pull request merged**
