### PR TITLE
Bo with constraints

### PR DESCRIPTION
**Pull request by bpapaspyros**
**Work in progress**

Initial attempt on bo with constraints

### CODE REVIEW

**Comment by costashatz** [comment]
@bpapaspyros should we merge? Is it working?

**Comment by bpapaspyros** [comment]
Seems to be working fine. I still need to correct a few things in the best_sample function, because it returns the best sample overall not the best feasible one. So I am not sure if it is ready for merging just yet. Also I need to update the comments etc, but this is not that urgent (it is going to be in the experimental anyway)

**Comment by costashatz** [comment]
> Seems to be working fine. I still need to correct a few things in the best_sample function, because it returns the best sample overall not the best feasible one. So I am not sure if it is ready for merging just yet. Also I need to update the comments etc, but this is not that urgent (it is going to be in the experimental anyway)

OK. Do the best_sample changes and then we can merge..

**Comment by bpapaspyros** [comment]
Should be **OK** to merge

**Comment by costashatz** [comment]
For me it's **OK**.

**Comment by jbmouret** [comment]
OK for me. You can merge.

**Comment by LQY404** [comment]
hello, i'm ready to use Limbo to solve our optimize problem with constraint, but i find the branch of constraint BO was deleted. I want to know that is it any problem of this bracnh, and can i use the old example of the branch to run my experiment? thanks.

**Pull request merged**
