### PR TITLE
Fix for #151

### PR DESCRIPTION
**Pull request by costashatz**
As discussed in #151, I added a question in the FAQ. Probably it needs some rephrasing..

### CODE REVIEW

**Comment by jbmouret** [comment]
Should we add the opposite assertion (for consistency): throw an assert if
we do not have NoLFOpt but hp_period == -1?

I think this situation could result in a nasty bug if the HP needs to be
optimized.

**Comment by costashatz** [comment]
> Should we add the opposite assertion (for consistency): throw an assert if
> we do not have NoLFOpt but hp_period == -1?

We could. But this would go into `BOptimizer` and thus it is not that easy to check the model type. An alternative solution would be to transfer all the HP Optimization to the GP. This would mean that the `hp_period` would be a parameter of the GP model. Then it is easy to create both assertions and I think it could be cleaner for the user. What do you think?

**Comment by jbmouret** [comment]
Didn't we have a long thread about where to call the optimization?

**Comment by costashatz** [comment]
> Didn't we have a long thread about where to call the optimization?

I honestly do not remember.

I cannot see an easy way to provide the second assertion.. Do you have any other ideas?

**Comment by jbmouret** [comment]
Maybe we could add it in the destructor of the optimizer if it is never
called?

**Comment by costashatz** [comment]
> Maybe we could add it in the destructor of the optimizer if it is never
> called?

It's not a bad idea, but we have 3 different structs for optimizing the hyperparameters. This means we should add the same code to each of them. I am OK with it if you are..

**Comment by jbmouret** [comment]
They could all inherit from the same abstract class, to avoid duplicating
this kind of logic.

**Comment by jbmouret** [comment]
Overall, I think that everything that prevents us to make buggy experiments
is a good idea, even if it adds some 'complexity' and remove some elegance.

**Comment by costashatz** [comment]
> Overall, I think that everything that prevents us to make buggy experiments
> is a good idea, even if it adds some 'complexity' and remove some elegance.

I agree with you. I will do it in this branch to avoid making a separate PR.

**Comment by costashatz** [comment]
@jbmouret Now it should be ok.

**Comment by jbmouret** [comment]
Can't we have all this in a single class and inherit?

**Comment by costashatz** [comment]
Done!

**Comment by jbmouret** [comment]
**OK for me**

**Comment by costashatz** [comment]
We should also merge this...

**Comment by jbmouret** [comment]
Working on it.

**Pull request merged**
