### PR TITLE
Formatting Code Tool

### PR DESCRIPTION
**Pull request by costashatz**
I am adding [clang-format](http://llvm.org/releases/3.6.1/tools/clang/docs/ClangFormat.html) in order to be able to automatically format the code. I will add small instructions in the Wiki.

### CODE REVIEW

**Comment by costashatz** [comment]
Here's the wiki page explaining how to use the tool: [Wiki](https://github.com/resibots/limbo/wiki/Auto-Formatting-Code).

**Comment by fedeallocati** [comment]
I have run the tool to both the source code of limbo, and my experiments, and everything went ok.

**I approve this PR.**

**Comment by fedeallocati** [comment]
@dogoepp you should check the styling that it produces, to see if you like it/agree with it

**Comment by jbmouret** [comment]
I think the script should call clang-format and not clang-format-3.6:
- on my mac, I have clang-format but not clang-format-3.6
- on the next Ubuntu, you will a different version of clang-format

**Comment by jbmouret** [comment]
A few more questions:
- Is there a way to keep empty bodies on the same line as the method/struct declaration? For instance:
```  struct parego : public defaults::parego {};
````
vs 
```
struct parego : public defaults::parego
{
 };
````
- same thing with empty constructors

Maybe AllowShortBlocksOnASingleLine (bool)?

- about the curly braces on their own line... After having done this for years, I actually switched to a denser format that allows me to read more code at once. Somehow, it looks more like Python, for instance. Would it be possible to switch to the K&R/Stroustrup style? http://www.stroustrup.com/bs_faq2.html (see the question about the layout). In short, curly braces on their own line when beginning a function, on the current line in all the other cases. Otherwise, I vote for curly brace on the current line (not on their own line)

**Comment by costashatz** [comment]
@jbmouret 
- But in Ubuntu there's no official clang-format package. It only has clang-format-* packages. We could add a simple symbolic link. What do you think? I took the assumption that we will stay into one version of clang-format as they are changing/adding functionalities and we should upgrade to them with caution.
- `AllowShortBlocksOnASingleLine` does not do anything to the braces. I am turning to `Stroustrup` (clang-format has one config named Stroustrup) version of braces. Check the commits to come.

**Comment by jbmouret** [comment]
On 15 Oct 2015, at 21:42, Konstantinos Chatzilygeroudis <notifications@github.com> wrote:

> @jbmouret
> 
> 	� But in Ubuntu there's no official clang-format package. It only has clang-format-* packages. We could add a simple symbolic link. What do you think? I took the assumption that we will stay into one version of clang-format as they are changing/adding functionalities and we should upgrade to them with caution.

In that case, we will have to do it �the hard way� by searching for the available version in your script. This should not be hard to test both options and see which binary is available.

> 	� AllowShortBlocksOnASingleLine does not do anything to the braces. I am turning to Stroustrup (clang-format has one config named Stroustrup) version of braces. Check the commits to come.

OK.

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
@jbmouret 

The issues should be fixed. I search first for `clang-format` and then for specific `clang-format-3.6`.

I will fix the conflicts and push the results.

**Comment by costashatz** [comment]
@jbmouret , @fedeallocati , @dogoepp 

Check and confirm this PR.

**Comment by fedeallocati** [comment]
Looks good, although it still has the problem of the empty structs, just that now it is:
```  
struct parego : public defaults::parego {
};
```
Nevertheless, I can get used to any style, and this looks good to. Also rechecked that the code compiles and tests passes.
**I approve this PR.**

**Comment by jbmouret** [comment]
OK for me with the last version.

**Comment by dogoepp** [comment]
OK

Looks fine for me too, as for the format.

**Pull request merged**
