### PR TITLE
Macro params

### PR DESCRIPTION
**Pull request by jbmouret**

### CODE REVIEW

**Comment by costashatz** [comment]
Can you make it to have the output stream as a parameter? That way we could easily write them to files using filestreams. Or is it too much for a macro?

**Comment by fedeallocati** [comment]
There is no need to replace SFERES_CONST here, since we are not using it. I will try after lunch to see if it compiles with Intel's Compiler

**Comment by jbmouret** [comment]
> Can you make it to have the output stream as a parameter? That way we could easily write them to files using filestreams. Or is it too much for a macro?

Done.



> There is no need to replace SFERES_CONST here, since we are not using it. I will try after lunch to see if it compiles with Intel's Compiler

Done

**Comment by costashatz** [comment]
Compiles just fine! Should we add some simple tests?

**Comment by jbmouret** [comment]
I do not know how to test this (and this is not critical).

**Comment by costashatz** [comment]
> I do not know how to test this (and this is not critical).

In that case, **I approve**

**Comment by fedeallocati** [comment]
Just checked and works fine with ICC.
**I approve**

**Pull request merged**
