### PR TITLE
Remove all blacklists

### PR DESCRIPTION
**Pull request by costashatz**
As discussed with @jbmouret, we should remove the blacklists.

### CODE REVIEW

**Comment by costashatz** [comment]
@jbmouret you should only fix the uml..

**Comment by jbmouret** [comment]
**OK for me**

**Comment by costashatz** [comment]
> OK for me

I have one question: as you can see [here](https://github.com/resibots/limbo/blob/remove_bl/src/limbo/bayes_opt/bo_base.hpp#L233-L234) we still have one possible way of throwing an `EvaluationError` exception, but we are not catching it. What should we do? Just leave it as it is or catch it (but then do what?)?

**Comment by jbmouret** [comment]
Good point. I think we can keep it: it will stop the algorithm, which is
not the worst behavior.

**Comment by costashatz** [comment]
> Good point. I think we can keep it: it will stop the algorithm, which is
> not the worst behavior.

OK. Then if no one has any objection, I will **merge**..

**Pull request merged**
