### PR TITLE
Added PARAM_ARRAY and STRING macros (copied from sferes)

### PR DESCRIPTION
**Pull request by fedeallocati**
I have used this feature for my experiments, and I think it's okay to add it to the codebase

### CODE REVIEW

**Comment by costashatz** [comment]
It'd be good if you wrote some examples/tests (in their respective folders), so that we can easily check them.

**Comment by jbmouret** [comment]
I agree with Konstantinos. You should a unit test for this.
� JBM

On 16 Oct 2015, at 18:43, Konstantinos Chatzilygeroudis <notifications@github.com> wrote:

> It'd be good if you wrote some examples/tests (in their respective folders), so that we can easily check them.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
Done, added tests for all the macro functionalities

**Comment by fedeallocati** [comment]
Btw, I was thinking it maybe good to have a macro por defining Eigen Vectors params. For example, when using as mean function the MeanConstant, it expects a Vector, and the only way to define it is manually coding the function in the parameter struct, like:
```
struct Params {
   struct meanconstant {
        static Eigen::VectorXd constant() { return Eigen::Vector3d(0, 0, 0); };
    };
};
```
It should be easy to do it with variadic macro parameters plus Eigen comma initializer. If you think it's suitable, I can add it.

**Comment by jbmouret** [comment]
It is a good idea.

If it does not work, we can also use a Eigen::Map:
http://eigen.tuxfamily.org/dox/group__TutorialMapClass.html

On 18 Oct 2015, at 18:12, Federico Allocati <notifications@github.com> wrote:

> Btw, I was thinking it maybe good to have a macro por defining Eigen Vectors params. For example, when using as mean function the MeanConstant, it expects a Vector, and the only way to define it is manually coding the function in the parameter struct, like:
> 
> struct Params {
>    struct meanconstant {
>         static Eigen::VectorXd constant() { return Eigen::Vector3d(0, 0, 0); };
>     };
> };
> 
> It should be easy to do it with variadic macro parameters plus Eigen comma initializer. If you think it's suitable, I can add it.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
All right, I know the Eigen Map, have used it before. Will check which of
the two approaches is faster and add the change.

2015-10-18 22:14 GMT+02:00 JB Mouret <notifications@github.com>:

**Comment by fedeallocati** [comment]
Added the Vector macro. I did some benchmark, comparing between 3 implementations:
```
#define BO_PARAM_VECTORMAP(Type, Name, ...) \
    static const Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>  Name() \
    {                                                    \
        static constexpr Type _##Name[] = {__VA_ARGS__}; \
        return Eigen::Map<const Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>>(_##Name); \
    }

#define BO_PARAM_VECTORMAP2(Type, Name, ...) \
    static const Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>  Name() \
    {                                                    \
        static constexpr Type _##Name[] = {__VA_ARGS__}; \
        static Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>  _##Name_map = Eigen::Map<const Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>>(_##Name); \
        return _##Name_map; \
    }

#define BO_PARAM_VECTORCOMMA(Type, Name, ...) \
    static const Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>  Name() \
    { \
        static Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1> _##Name; \
        _##Name << __VA_ARGS__; \
        return _##Name; \
    }
```
And the first one won, as you can see in the following plot (y axis is milliseconds time of 1000000000 additions using the parameter vector as right hand operator, each variant was run 500 times):
param_vector_benchmark
So I choose that one and added it to the macros as BO_PARAM_VECTOR. Also added the corresponding test in test_macros.cpp

Waiting for approval to merge

**Comment by costashatz** [comment]
All the tests pass and as far as I can check everything seems fine.

**I approve**

**Comment by jbmouret** [comment]
There is a missing & in the return type of map2, I think.
```
#define BO_PARAM_VECTORMAP2(Type, Name, ...) \
    static const Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>&  Name() \
    {                                                    \
        static constexpr Type _##Name[] = {__VA_ARGS__}; \
        static Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>  _##Name_map = Eigen::Map<const Eigen::Matrix<Type, __VA_NARG__(__VA_ARGS__), 1>>(_##Name); \
        return _##Name_map; \
    }
```

... because my intuition is that we should avoid making a copy here!

(Also, if you did your test like`auto x = name()`, then the cost of the copy is not visible. What did you test?)

**Comment by fedeallocati** [comment]
The code for my test:
```
struct Params {
    struct test {
        BO_PARAM_VECTOR(double, a, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0);
        BO_PARAM_VECTORMAP2(double, b, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0);
        BO_PARAM_VECTORCOMMA(double, c, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0);
    };
};

int main() {
    const long long int iters = 1000000000;
    auto t1 = std::chrono::steady_clock::now();
    Eigen::VectorXd r(6);
    r.setZero();
    for (long long int i = 0; i < iters; i++){ 
        r += Params::test::a();
    }
    auto time_running_map = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - t1).count();
    r.setZero();
    t1 = std::chrono::steady_clock::now();
    for (long long int i = 0; i < iters; i++){ 
        r += Params::test::b();
    }
    auto time_running_map2 = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - t1).count();    
    r.setZero();
    t1 = std::chrono::steady_clock::now();
    for (long long int i = 0; i < iters; i++){ 
        r += Params::test::c();
    }
    auto time_running_comma = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - t1).count();

    std::ofstream res_file("results_" + limbo::misc::date() + "_" + limbo::misc::getpid() + ".dat", std::ofstream::app);
    res_file << time_running_map << " " << time_running_map2 << " " << time_running_comma  << std::endl;

    return 0;
}
```
Will run the tests again with the reference

**Comment by fedeallocati** [comment]
Even without the reference, the first option wins (maybe the compiler is doing return value optimization?). 
The details of this run:

||map|map2|comma|
|---:|---:|---:|---:|
|Upper whisker|7566.875|10451.625|15697.875|
|3rd quartile|6368.750|9686.250|14283.750|
|Median|5663.000|9190.500|13364.000|
|1st quartile|5570.000|9176.000|13341.000|
|Lower whisker|5408.000|9057.000|12785.000|

And the plot:
param_vector_benchmark

**Comment by jbmouret** [comment]
I am surprised: the reference version should have almost 0 overhead because everything is computed only once.

Any idea why it can be slow?

On 19 Oct 2015, at 16:55, Federico Allocati <notifications@github.com> wrote:

> Even without the reference, the first option wins (maybe the compiler is doing return value optimization?). 
> The details of this run:
> 
> map	map2	comma
> Upper whisker	7566.875	10451.625	15697.875
> 3rd quartile	6368.750	9686.250	14283.750
> Median	5663.000	9190.500	13364.000
> 1st quartile	5570.000	9176.000	13341.000
> Lower whisker	5408.000	9057.000	12785.000
> And the plot:
> 
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
I'm not really sure, I guess we should have to do some low level profiling, or maybe look at the generated assembly code (please, no :smile:  :gun: ) to get to the bottom of the issue. Putting the feets on the ground I think it's not worth investigating it now, since you see I did an exagerated amount of 1000000000 acceses to be able to see visible differences, and there is a diference of less than 3 seconds in the performance

**Comment by jbmouret** [comment]
I agree that we should waste our time to understand this in detail. Still, this is surprising. Also, this way of defining parameters is designed to have a 0 overhead, therefore this unexplained overhead is disappointing.

At any rate, let's take the fastest version.

**Comment by fedeallocati** [comment]
Just to be sure that we aren't getting overhead, I will benchmark tomorrow
the time of the operación having directly the vector, instead of accesing
the parameter

**Comment by fedeallocati** [comment]
So, I have runned 4 cases: No parameter (performing the addition directly with a previously declareted Vector), Parameter declaring the map in the return (BO_PARAM_VECTORMAP), Parameter creating a static map and returning a reference (BO_PARAM_VECTORMAP2 with the modification JB said), Parameter creating a static map and returning without reference (orignal BO_PARAM_VECTORMAP2).
The results:

||no param|returning map|static map ref|static map copy|
|---:|---:|---:|---:|---:|
|Upper whisker|4942.750|6462.250|11541.125|10338.875|
|3rd quartile|4487.500|5878.750|10870.250|9395.750|
|Median|4245.000|5529.500|10433.000|8802.500|
|1st quartile|4184.000|5489.750|10423.000|8767.000|
|Lower whisker|4022.000|5315.000|10375.000|8629.000|

param_vector_benchmark

We see that even in the fastest case we get a little overhead, which naturally sucks, but I can't think of another alternative to try.

**Comment by costashatz** [comment]
Can you provide us the code for each test case?

**Comment by jbmouret** [comment]
Thanks. Let�s use the fastest!

On 20 Oct 2015, at 12:54, Federico Allocati <notifications@github.com> wrote:

> So, I have runned 4 cases: No parameter (performing the addition directly with a previously declareted Vector), Parameter declaring the map in the return (BO_PARAM_VECTORMAP), Parameter creating a static map and returning a reference (BO_PARAM_VECTORMAP2 with the modification JB said), Parameter creating a static map and returning without reference (orignal BO_PARAM_VECTORMAP2).
> The results:
> 
> no param	returning map	static map ref	static map copy
> Upper whisker	4942.750	6462.250	11541.125	10338.875
> 3rd quartile	4487.500	5878.750	10870.250	9395.750
> Median	4245.000	5529.500	10433.000	8802.500
> 1st quartile	4184.000	5489.750	10423.000	8767.000
> Lower whisker	4022.000	5315.000	10375.000	8629.000
> 
> 
> We see that even in the fastest case we get a little overhead, which naturally sucks, but I can't think of another alternative to try.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
@costashatz It's up there, just changed the macros and added a case without using the parameter struct.
If you want, I could upload the test code to the benchmarks folder

**Comment by costashatz** [comment]
Sorry! Didn't see it the first time.

Let's use the fastest one.

**Comment by fedeallocati** [comment]
Noticed that the formatting tool breaks one of the macros. Reported in #22

**Comment by costashatz** [comment]
Restore the branch and apply this quick fix: use `clang-format off` and `clang-format on`. You can see examples in the code for lambda functions.

I am investigating if there's a better way to do it.

**Pull request merged**
