### PR TITLE
Gradient check test via finite differences

### PR DESCRIPTION
**Pull request by costashatz**
Added a test for checking our gradient of the likelihood function in the GP. To get the proper gradients I had to remove the scaling and the bounds we previously had (just because BayesOpt was using them). Probably, we can make it work with the scaling/bounds, but I do not really want to lose more time on this.

### CODE REVIEW

**Comment by costashatz** [comment]
@jbmouret @Aneoshun should I merge?

**Comment by jbmouret** [comment]
Ok for me

**Comment by costashatz** [comment]
It's weird... I am still getting some `nlopt failure` errors when optimizing with the correct gradients.. Do you have any other ideas on what may be wrong?

**Comment by costashatz** [comment]
> It's weird... I am still getting some nlopt failure errors when optimizing with the correct gradients.. Do you have any other ideas on what may be wrong?

I cannot find any issue in our code. It seems it is an LBFGS issue of NLOpt: see [here](https://github.com/JuliaOpt/NLopt.jl/issues/33) and [here](http://nlopt-discuss.ab-initio.mit.narkive.com/1I714PMd/how-to-debug-nlopt-failure). **Merging...**

**Pull request merged**
