### PR TITLE
Split files into folders

### PR DESCRIPTION
**Pull request by costashatz**
Split files/classes into folders. Each subfolder has its own namespace and most files have only 1 class (some have 2 classes - e.g. matern kernel has both 3 1/2 and 5 1/2).

I have the following doubts:
- Are the names (for namespaces/folders) what we want? I have full names now. Are they too long?
- In the mean functions, I am repeating the mean word (mean_constant, mean_data e.t.c.). Should we change that? For the moment, I just named the files after the classes.
- Where should we put the bayesian optimizers (boptimizer, nsbo etc)? I have them in a separate folder, but without a namespace as they are the main classes of this library. What do you think it's cleaner?

### CODE REVIEW

**Comment by fedeallocati** [comment]
Comments:
- parallel.hpp shouldn't be in it's own folder or maybe in misc?
- acquisition_functions.hpp shouldn't include ehvi.hpp also?
- maybe the bayesian optimizers can be in the limbo folder(instead of in their own folder), since as you said, they are the core of this library
- in bo_base.hpp instead of including everything, we should include only the requiered files for the defaults
- even though the initialization NoInit does nothing, I would put it on it's own file, just to be consistent
- I vote on separating mattern 3 1/2 and 5 1/2, as I said before, just for consistency
- As kernel functions doesn't start with "Kernel" I would do the same for mean functions and remove "Mean"
- You are probably going to hang me for this but: Kernel and Mean functions are specific to the GP model, and I have the feeling that they shouldn't be in the root of limbo, but in something like models/gp/kernel_functions. I know that for now it's our only model, but maybe it's better for clarity to do it that way
- limbo.hpp shouldn't include all header files?

**Comment by costashatz** [comment]
> parallel.hpp shouldn't be in it's own folder or maybe in misc?

Yeap you are right. Forgot it.

> acquisition_functions.hpp shouldn't include ehvi.hpp also?

I think they do. Check [this](https://github.com/resibots/limbo/blob/file_split/src/limbo/acquisition_functions/ehvi.hpp).

> maybe the bayesian optimizers can be in the limbo folder(instead of in their own folder), since as you said, they are the core of this library

Thinking about it more, I think they are better into a separate folder, but without a namespace.

> even though the initialization NoInit does nothing, I would put it on it's own file, just to be consistent
> I vote on separating mattern 3 1/2 and 5 1/2, as I said before, just for consistency

No problem with that. Will do.

> As kernel functions doesn't start with "Kernel" I would do the same for mean functions and remove "Mean"

That's what I was thinking about.

> You are probably going to hang me for this but: Kernel and Mean functions are specific to the GP model, and I have the feeling that they shouldn't be in the root of limbo, but in something like models/gp/kernel_functions. I know that for now it's our only model, but maybe it's better for clarity to do it that way

Maybe a better way is to have the kernel and mean functions folders in the following form: `kernel_functions/model_name/...`.

> limbo.hpp shouldn't include all header files?

Not all of them. The basic headers to get limbo working. I will check again. Do you think something essential is missing?

**Comment by fedeallocati** [comment]
https://github.com/resibots/limbo/blob/file_split/src/limbo/acquisition_functions/acquisition_functions.hpp

>>acquisition_functions.hpp shouldn't include ehvi.hpp also?

>I think they do. Check  [this](https://github.com/resibots/limbo/blob/file_split/src/limbo/acquisition_functions/ehvi.hpp).

I meant  [this](https://github.com/resibots/limbo/blob/file_split/src/limbo/acquisition_functions/acquisition_functions.hpp).

>>maybe the bayesian optimizers can be in the limbo folder(instead of in their own folder), since as you said, they are the core of this library

>Thinking about it more, I think they are better into a separate folder, but without a namespace.

Why? I feel the opposite, keeping them in the limbo folder. Or if not, putting them in their own namespace.

>>You are probably going to hang me for this but: Kernel and Mean functions are specific to the GP model, and I have the feeling that they shouldn't be in the root of limbo, but in something like models/gp/kernel_functions. I know that for now it's our only model, but maybe it's better for clarity to do it that way

>Maybe a better way is to have the kernel and mean functions folders in the following form: kernel_functions/model_name/

I disagree with that, because it assumes that all models will have kernel/mean functions. A silly example: if I add a Linear Regression model, it won't have any kernel or mean function. 
Also, I have this same feeling with the acquisition functions. In *bo_base.hpp* there is a comment that says `// WARNING: you have to specify the acquisition  function if you use a custom model`, so I think it's nice if our acquisition functions are somewhere "under" GP, like for example *models/gp/acquisition_functions*

>>limbo.hpp shouldn't include all header files?

>Not all of them. The basic headers to get limbo working. I will check again. Do you think something essential is missing?

The meaning of "basic" depends on the case of use. If one just wants to have a simple bayesian optimizer, and don't "tune" anything, then one can include *boptimizer.hpp*, which has all default values (included from *bo_base.hpp*). Then, if he wants customization, then he should include the specific files he wants to use (or include *limbo.hpp* and pay the extra cost of including/preprocessing/parsing/compiling(non-templated classes/functions) the files).

Things that I see that are not being included (even though they may be included by some of the already included files: optimizers (which is missing an *optimizers.hpp* file), bayesian_optimizers(only *boptimizer.hpp* is included), *parallel.hpp*.

**Comment by costashatz** [comment]
> I meant this.
> The meaning of "basic" depends on the case of use. If one just wants to have a simple bayesian optimizer, and don't "tune" anything, then one can include boptimizer.hpp, which has all default values (included from bo_base.hpp). Then, if he wants customization, then he should include the specific files he wants to use (or include limbo.hpp and pay the extra cost of including/preprocessing/parsing/compiling(non-templated classes/functions) the files).

We should really decide what we want to included in the `limbo.hpp`. I am leaning towards create 2-3 general include files for some "usual" cases and then write in the docs in detail what every file does.

> Why? I feel the opposite, keeping them in the limbo folder. Or if not, putting them in their own namespace.

@jbmouret What do you think? I really do not have a strong preference. Just that they are too many to keep them in the `limbo` folder.

> I disagree with that, because it assumes that all models will have kernel/mean functions. A silly example: if I add a Linear Regression model, it won't have any kernel or mean function. 
> Also, I have this same feeling with the acquisition functions. In bo_base.hpp there is a comment that says // WARNING: you have to specify the acquisition function if you use a custom model, so I think it's nice if our acquisition functions are somewhere "under" GP, like for example models/gp/acquisition_functions

A Linear Regression model isn't doing bayesian optimization, right? The library is called `A lightweight framework for Bayesian and model-based optimisation of black-box functions`. We want the library to be generic, but its main goal is to provide a bayesian optimization framework.

In addition, the way I suggested, if a model does not have a kernel/mean function, the folder would not exist. We won't assume anything. Also, for example, the `Constant` mean function could be applied to several models, so it makes sense to put it in the main `mean_functions` folder. Kernel and mean functions are model specific, but they can share common interface/information, so I think they should be in a separate folder.

**Comment by fedeallocati** [comment]
El oct. 27, 2015 6:40 PM, "Konstantinos Chatzilygeroudis" <
notifications@github.com> escribió:
>>
>> I meant this.
>> The meaning of "basic" depends on the case of use. If one just wants to
have a simple bayesian optimizer, and don't "tune" anything, then one can
include boptimizer.hpp, which has all default values (included from
bo_base.hpp). Then, if he wants customization, then he should include the
specific files he wants to use (or include limbo.hpp and pay the extra cost
of including/preprocessing/parsing/compiling(non-templated
classes/functions) the files).
>
> We should really decide what we want to included in the limbo.hpp. I am
leaning towards create 2-3 general include files for some "usual" cases and
then write in the docs in detail what every file does.
>>
>> Why? I feel the opposite, keeping them in the limbo folder. Or if not,
putting them in their own namespace.
>
> @jbmouret What do you think? I really do not have a strong preference.
Just that they are too many to keep them in the limbo folder.
>>
>> I disagree with that, because it assumes that all models will have
kernel/mean functions. A silly example: if I add a Linear Regression model,
it won't have any kernel or mean function.
>> Also, I have this same feeling with the acquisition functions. In
bo_base.hpp there is a comment that says // WARNING: you have to specify
the acquisition function if you use a custom model, so I think it's nice if
our acquisition functions are somewhere "under" GP, like for example
models/gp/acquisition_functions
>
> A Linear Regression model isn't doing bayesian optimization, right? The
library is called A lightweight framework for Bayesian and model-based
optimisation of black-box functions. We want the library to be generic, but
its main goal is to provide a bayesian optimization framework.
What I meant is to use a LR model instead of a GP. It would still be
bayesian optimization, just with a different model.

>
> In addition, the way I suggested, if a model does not have a kernel/mean
function, the folder would not exist. We won't assume anything. Also, for
example, the Constant mean function could be applied to several models, so
it makes sense to put it in the main mean_functions folder. Kernel and mean
functions are model specific, but they can share common
interface/information, so I think they should be in a separate folder.
In the way I suggested the folder also would not exist  if the model don't
need it.
In the way we have it now, not all of them can be reused, because they
assume  the interface of the GP (for example mean_data expects a
mean_observation function in the model).
Anyway, I don't know if the plan is to include different models at some
point, or not.

**Comment by fedeallocati** [comment]
Sorry, answering from the cellphone messed things up. Answering again:

>A Linear Regression model isn't doing bayesian optimization, right? The library is called `A lightweight framework for Bayesian and model-based optimisation of black-box functions`. We want the library to be generic, but its main goal is to provide a bayesian optimization framework.

What I meant is to use a LR model instead of a GP. It would still be bayesian optimization, just with a different model.

>In addition, the way I suggested, if a model does not have a kernel/mean function, the folder would not exist. We won't assume anything. Also, for example, the `Constant` mean function could be applied to several models, so it makes sense to put it in the main `mean_functions` folder. Kernel and mean functions are model specific, but they can share common interface/information, so I think they should be in a separate folder.

In the way I suggested the folder also would not exist if the model doesn't need it.
Also, in the way we have it now, not all of them can be reused, because some of them assume the interface of the GP (for example mean_data expects a mean_observation() function in the model passed).
Anyway, I don't know if the plan is to include different models at some point, or not, so in that depends the choice.

**Comment by jbmouret** [comment]
A few quick comments:
- I prefer shorter names, even if they can be a bit cryptic sometimes: this is easier to type, and faster to read (e.g. bayesian_optmization=bo, mean_function=mean_fun, inner_optimization=inner_opt, kernel_functions=k_fun ? or even shorter, like mfun, iopt, kfun)
- directories = namespaces, therefore if you put some files in a directory, then they have to be in a namespace with the same name.
- if possible, we should avoid to "over-nest" directories.

**Comment by costashatz** [comment]
So, to sum up:

- I will shorten the names, which is something I prefer too.
- Directories = namespaces.
- Not "over-nest" directories.
- limbo.hpp includes every file of limbo. *(I am not sure about this one)*

In consequence, I suggest that the kernel and mean functions remain in separate folders until we find the need of an additional model (other than GPs) and we will discuss it again when the time comes.

What do you think?

Also, what should we do with the directories (`cmaes` and `ehvi`) that are outside `limbo` directory. Should we leave them there?

**Comment by jbmouret** [comment]
Do we really need to split inner_opt and opt?

**Comment by fedeallocati** [comment]
When we make the generic optimization, it won't be neccesary. But for now I think it's best to keep it the way it is

**Comment by costashatz** [comment]
I agree. I will create a separate PR to merge them.

**Comment by jbmouret** [comment]
- I do not know about par and misc, maybe we could put everything in a "tools" directory?
- stop_crit does not sound very nice. What about "stop_fun", to be consistent?
- why is "models" plural whereas all the other names are singular? there are many kernel_functions, but it is not kerne_funs.

**Comment by jbmouret** [comment]
A last point: what is the policy for *_fun? that everything in a *_fun is a functor? in that casse, this should be the same for the inner_opt, I think.

I am not 100% convinced by the "bayes_opt" namespace, but I do not know what to propose instead (because we have 3 *opt* namespaces!). Again, if boptimizer follows the same interface as the other optimiser, we could merge everything in "opt".

**Comment by costashatz** [comment]
> I do not know about par and misc, maybe we could put everything in a "tools" directory?

I didn't like it either. I will merge them into a tools directory/namespace.

> why is "models" plural whereas all the other names are singular? there are many kernel_functions, but it is not kerne_funs.

`kernel_fun` is plural but omitted. Since, `models` could not be omitted, I chose the plural. I really do not have any preference on this one. I can make them all singular.

> A last point: what is the policy for *_fun? that everything in a *_fun is a functor? in that casse, this should be the same for the inner_opt, I think.

To be honest, I just followed the names that were already there with minor alterations. We can decide on what will be the policy. From the perspective that I see it, every in `*_fun` should be a functor. I don't care that much about `inner_opt` as it will be changes anyway.

> I am not 100% convinced by the "bayes_opt" namespace, but I do not know what to propose instead (because we have 3 opt namespaces!). Again, if boptimizer follows the same interface as the other optimiser, we could merge everything in "opt".

I didn't know what to choose. I know for sure that `inner_opt` and `opt` will be merged. For `bayes_opt` I am not completely sure that we will be able to provide the same interface with the other optimizers. Also, bayesian optimizers are the core of the library and makes sense to have them in a separate folder/namespace.

**Comment by jbmouret** [comment]
> I am not 100% convinced by the "bayes_opt" namespace, but I do not know what to propose instead (because we have 3 opt namespaces!). Again, if boptimizer follows the same interface as the other optimiser, we could merge everything in "opt".
> I didn't know what to choose. I know for sure that inner_opt and opt will be merged. For bayes_opt I am not completely sure that we will be able to provide the same interface with the other optimizers. Also, bayesian optimizers are the core of the library and makes sense to have them in a separate folder/namespace.

**Comment by fedeallocati** [comment]
> - I do not know about par and misc, maybe we could put everything in a "tools" directory?

I think I prefer putting par inside misc. We could also add in misc the helper function to return 1-d Vector when optimizing a double.

> - stop_crit does not sound very nice. What about "stop_fun", to be consistent?

I had something to say with regards to this, which maybe is for a different discussion. One would think that as they are called stopping criterions, they would return true when the optimizer has to stop, and false otherwhise. But currently it's the opposite, they have to return true when the optimizer has to continue running, which is anti-intuitive. Is there a reason for this naming/behaviour?

> - why is "models" plural whereas all the other names are singular? there are many kernel_functions, but it is not kerne_funs.
A last point: what is the policy for *_fun? that everything in a *_fun is a functor? in that casse, this should be the same for the inner_opt, I think.

The same applies to stats, they are in plural, and they are functors, shouldn't them be renamed to stat_fun?

>I didn't know what to choose. I know for sure that inner_opt and opt will be merged. For bayes_opt I am not completely sure that we will be able to provide the same interface with the other optimizers. Also, bayesian optimizers are the core of the library and makes sense to have them in a separate folder/namespace.

I agree that bayesian optimizers won't have the same interface as the other optimizers (but maybe we could add that interface, to be able to use them as standard optimizers, soooo meta), and even if they do, they are the core of the library.

**Comment by jbmouret** [comment]
> I had something to say with regards to this, which maybe is for a different discussion. One would think that as they are called stopping criterions, they would return true when the optimizer has to stop, and false otherwhise. But currently it's the opposite, they have to return true when the optimizer has to continue running, which is anti-intuitive. Is there a reason for this naming/behaviour?

No reason, but either we change the name or we change the behaviour. This is the right time to do this...

**Comment by costashatz** [comment]
Summing up again (after reading the comments and talking with @jbmouret ):

- I think we should drop all the `_fun` and just keep plain names.
- All names should be singular.
- For this PR, we keep `bayes_opt` as it is and I will see if I can create the same interface as the other optimizers to merge them in a single folder/namespace. But **please provide better names for** `bayes_opt`, if you feel it is not the best name.
- About the `stop criteria`, we could reverse the functionality/behavior. I really do not have any strong preference.

**Comment by costashatz** [comment]
@jbmouret and @fedeallocati I am waiting on you to either approve the PR or make comments about the `bayes_opt` name or the `stop criteria` behavior. I am reminding that `inner_opt` and `opt` will be merged in a new PR.

**Comment by fedeallocati** [comment]
On the include guards, shouldn't we also remove "function"? e.g `#define MEAN_CONSTANT_HPP_' instead of `#define MEAN_FUNCTIONS_CONSTANT_HPP_'

**Comment by costashatz** [comment]
> On the include guards, shouldn't we also remove "function"? e.g #define MEAN_CONSTANT_HPP_' instead of#define MEAN_FUNCTIONS_CONSTANT_HPP_'

Yes. But since we have many things to clean, it'd be better to do it in a separate PR. At least that's my opinion on this one.

**Comment by jbmouret** [comment]
**OK for me** let's merge this and move add new PR for the next details.

**Comment by fedeallocati** [comment]
I would prefer to do the cleaning of the include guards in this PR, since it's directly related to the renaming/restructuring of files. I agree that the other things (stop_criteria behaviour and inner_opt-op merge) should be different PR

**Comment by costashatz** [comment]
OK. Can you do it? Because I am in the middle of something else?

**Comment by fedeallocati** [comment]
Ok. We should agree in some policy. Copying Boost, I suggest reflecting the file structure, for example:
`LIMBO_ACQUI_UCB_HPP`. Other suggestion?

**Comment by costashatz** [comment]
> Ok. We should agree in some policy. Copying Boost, I suggest reflecting the file structure, for example:
> LIMBO_ACQUI_UCB_HPP. Other suggestion?

I agree with this one.

**Comment by jbmouret** [comment]
I agree with this.

**Comment by fedeallocati** [comment]
Finished this. I have one more suggestion before merging: also inspired by boost, put the include files that just include all of the folder (e.g. `acqui/acquisition_functions.hpp`) in the root of limbo.
In that way, if someone want's for example to add all of the stats, he could do `#include <limbo/stats.hpp>`, which is nicer than `#include <limbo/stat/stats.hpp>`

**Comment by jbmouret** [comment]
OK for this.

On 28 Oct 2015, at 17:51, Federico Allocati <notifications@github.com> wrote:

> Finished this. I have one more suggestion before merging: also inspired by boost, put the include files that just include all of the folder (e.g. acqui/acquisition_functions.hpp) in the root of limbo.
> In that way, if someone want's for example to add all of the stats, he could do #include <limbo/stats.hpp>, which is nicer than #include <limbo/stat/stats.hpp>
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
> I have one more suggestion before merging: also inspired by boost, put the include files that just include all of the folder (e.g. acqui/acquisition_functions.hpp) in the root of limbo.
> In that way, if someone want's for example to add all of the stats, he could do #include <limbo/stats.hpp>, which is nicer than #include <limbo/stat/stats.hpp>

Done this.

**Comment by fedeallocati** [comment]
4 more things:
- Shouldn't we add group files for tools, model, opt and bayes_opt?
- We have to change the include guard in the moved files to match their location
- We keep the long names in the group files, or shorten them?
- Is it okay for tools to be plural? I think that just "tool" sounds a little akward, but asking as a matter of consistency

**Comment by costashatz** [comment]
> Shouldn't we add group files for tools, model, opt and bayes_opt?

We only have one model (the gp_auto and gp_automean will go away in the next PR), so we don't really need a group file. Same for `opt`. I will create one group file for `bayes_opt`.

> We have to change the include guard in the moved files to match their location

True.

> We keep the long names in the group files, or shorten them?

Let's shorten them. To be consistent.

> Is it okay for tools to be plural? I think that just "tool" sounds a little akward, but asking as a matter of consistency

It's okay to be plural. I mean it is a special folder.

**Comment by costashatz** [comment]
I think this PR is good. What do you think?

**Comment by fedeallocati** [comment]
- Any reason why you kept the "fun" in the group filenames?
- Why not making a group file for tools?
- I would make anyway a group file for models, to be consistent, and so in the future if we add different models, we just have to add them there

Besides that, I tried compiling and just found an issue, which hasn't too much to do with what we where doing here: When trying to compile the examples, it fails because `bo_multi.hpp` tries to include files from sferes, and since in the wscript it doesn't set SFERES as a uselib, it fails.
This problem happens because of the way the define `USE_SFERES` is defined in the waf configuration. Instead of defining it only if the targets use SFERES library, it defines it always, so limbo always think they are using sferes, even if in the build target it isn't defined.
I will fix this bug and try again.

**Comment by costashatz** [comment]
Now it's compiling.

**Comment by jbmouret** [comment]
I think we need to remove the _fun for the module headers.

**Comment by fedeallocati** [comment]
One thing we should do, to avoid warnings, is in the examples and tests only include the files that we use. If you want we can make that in another PR.
I compiled in my machine and in the kernel and works.

**I approve**

**Comment by fedeallocati** [comment]
> I think we need to remove the _fun for the module headers.

Also the other 2 things I said:
- Why not making a group file for tools?
-I would make anyway a group file for models, to be consistent, and so in the future if we add different models, we just have to add them there

**Comment by jbmouret** [comment]
Yes, for consistency, we should have a group file for each directory. (and yes, let's do the other things in another PR).

**Comment by fedeallocati** [comment]
I'm doing this changes. Want to propose also, to avoid confusion, rename the class Stat to StatBase. Someone disagrees?

**Comment by jbmouret** [comment]
OK for me.

**Comment by costashatz** [comment]
OK for me too.

**Comment by fedeallocati** [comment]
Finished. Compiled all_combinations_tests in the cluster correctly.
I took the liberty to organize include in files as follows:
1. Standard headers
2. Boost headers
3. TBB headers
4. Eigen headers
5. Sferes headers
6. Limbo headers
7. EHVI and CMAES headers

Sorry for being so obsessive :)
Check and approve if you think it's allright

**Comment by jbmouret** [comment]
*in theory*, we should swap 6&7... (and maybe put sferes at a higher rank).

**Comment by fedeallocati** [comment]
Sure, whatever you like, I just followed my instinct, not any guideline. Tell me how you prefer it and I can change it

**Comment by jbmouret** [comment]
The classic guideline is: the more you trust it, the higher you put it. Another guideline: limbo depends on sferes that depends on boost that depends on the STL, therefore standard headers > boost headers > sferes > limbo; sferes and limbo depend on Eigen (and CMAES), therefore boost headers > Eigen > sferes > limbo.

**Comment by fedeallocati** [comment]
How about this? 
1. Standard headers
2. Boost headers
3. Eigen headers
4. TBB headers
5. Sferes headers
6. EHVI and CMAES headers
7. Limbo headers

Between TBB and Eigen, Eigen is widely used, while TBB is only in a few files, so I would lower it's rank. The same goes for EHVI/CMAES and Sferes, they are uses on very specific places.

**Comment by costashatz** [comment]
> How about this? 
> 1. Standard headers
> 2. Boost headers
> 3. Eigen headers
> 4. TBB headers
> 5. Sferes headers
> 6. EHVI and CMAES headers
> 7. Limbo headers
> 
> Between TBB and Eigen, Eigen is widely used, while TBB is only in a few files, so I would lower it's rank. The same goes for EHVI/CMAES and Sferes, they are uses on very specific places.

Seems pretty good. We really need to close this PR.

**Comment by costashatz** [comment]
Done this.

**Comment by fedeallocati** [comment]
**I approve this PR**

**Comment by jbmouret** [comment]
**OK for me**

**Pull request merged**
