### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by costashatz**
This PR aims to fix travis.. It is **not to be merged** yet..

### CODE REVIEW

**Comment by costashatz** [comment]
This is ready to be merged... In a glance, testing our tests for:

- g++ and clang
- with or without libcmaes
- with or without nlopt
- with or without tbb

It works as expected.. We should **merge**..

**Comment by costashatz** [comment]
As soon as the tests pass, we should **merge**. In a glance, running our tests for:

- g++ and clang
- with or without libcmaes
- with or without nlopt
- with or without tbb
- one run for each compiler for the extensive tests with libcmaes, nlopt and tbb on

I am merging except if you feel like having the extensive tests run at each commit is too much (although it's not running on our machines).

**Comment by costashatz** [comment]
Should I merge?

**Comment by Aneoshun** [comment]
How long take the extensive tests?

**Comment by costashatz** [comment]
> How long take the extensive tests?

The limit for the free account is 50 minutes and up to 50 min, less than 1/4 were compiled.

**Comment by Aneoshun** [comment]
Hoo ok, I wasn't aware about the free account limit.
Then you can merge IMHO

**Comment by jbmouret** [comment]
too long... and there is a limit (15 minutes?) for Travis.

**Comment by costashatz** [comment]
If we want a commit to not run the travis ci (e.g. we just changed the README), we should include anywhere in the commit message `[ci skip]`.

**Merging...**

**Pull request merged**
