### PR TITLE
Fixed Stopping Criteria behaviour

### PR DESCRIPTION
**Pull request by fedeallocati**
- Changed Stopping Criteria structs to return true when the BO has to be stopped
- Changed the name of the method _pursue to _stop

### CODE REVIEW

**Comment by fedeallocati** [comment]
Probably, I just keep the same functionality as before. Changing it now.

**Comment by costashatz** [comment]
I think this is good now. **I approve**

**Comment by fedeallocati** [comment]
@jbmouret objections about this PR?

**Comment by jbmouret** [comment]
**OK for me**

**Pull request merged**
