### PR TITLE
use a c++-11 rng instead of calling eigen3 for tools::random_vector()

### PR DESCRIPTION
**Pull request by jbmouret**

### CODE REVIEW

**Comment by costashatz** [comment]
It's weird.. Now `nlopt_test` (no gradient) is failing some times with the new random vector.. Before it was no random.. I am checking it..

**Comment by costashatz** [comment]
So playing a little bit with it, my guess is the following:

- `LN_COBYLA` algorithm is a local derivative-free optimizer and thus it does not make sense to initialize it with a random point as a starting point. I am changing it to start from a meaningfully close point to the solution..

What do you think?

**Comment by jbmouret** [comment]
A classic use of local algorithms is to start them from different random points and use the best result. Don't we do this? When do we need to check that Limbo works with LN_COBYLA?

**Comment by costashatz** [comment]
> When do we need to check that Limbo works with LN_COBYLA?

There's a test for nlopt using a local gradient free algorithm..

> A classic use of local algorithms is to start them from different random points and use the best result.

I will do this..

**Comment by costashatz** [comment]
We can **merge** now..

**Comment by costashatz** [comment]
**Merging...**

**Pull request merged**
