### PR TITLE
Review of the documentation

### PR DESCRIPTION
**Pull request by dogoepp**
This long-lasting pull request is made to discuss the proposed changes to the documentation, and related questions.

The next comment will contain the first questions/comments.

### CODE REVIEW

**Comment by dogoepp** [comment]
# Compilation of the documentation #116

# Waf version
Should we write at some places in the docs which version of Waf is currently used for limbo, so that the users can check the documentation ?

**Comment by dogoepp** [comment]
# `tutorials/compilation.rst`

## around line 31:
```
* `NLOpt <http://ab-initio.mit.edu/wiki/index.php/NLopt>`_ with C++ binding: ::

    ./configure -with-cxx --enable-shared --without-python --without-matlab --without-octave
    make install
```

Are you sure for the single dash in -with-cxx ?

## around line 81:
```
* ``--boost-includes /path/to/boost-includes`` [.h]
* ``--boost-libs /path/to/boost-libraries`` [.a, .so, .dynlib]
```

What do the [.h] and the one next line mean ?

## around line 102
 Is the list of executed tests still the same ? I saw discussions that seemed to mention new tests.

**Comment by dogoepp** [comment]
# `tutorials/basic_example.rst`

## around line 1
What are the three cascading headers meaning ?

## around line 10
What about replacing "test" by something more specific, like "myExperiment" ?

## around line 93
> that we don't want to output any stats (by setting the dump period to -1)

I don't find this dump period, nor any -1 value in the example. Besides, I would interpret

```C++
struct bayes_opt_bobase {
  BO_PARAM(int, stats_enabled, true);
};
```

as telling to actually output the statistics.

**Comment by dogoepp** [comment]
# `tutorials/external_libs.rst`
## around line 15
Why the default behavior is to return 1 ? Why do we not use ``res`` ?

Why does the library python script have to have #! /usr/bin/env python ?

## around line 69
Where is `include_files` defined ? Who has to fill it ? (I expect that it is the user, but it's not very clear in the tutorial)

## around line 97
Same remarks as at line 69

## around lines 68 and 96
Why do we define the `res` variable to True but never use it again ?

## around line 241
Why return 1 both when we failed and succeeded ?

**Comment by jbmouret** [comment]
Good point. We should extract it automatically.

**Comment by costashatz** [comment]
> tutorials/external_libs.rst
> 
> around line 15
> 
> Why the default behavior is to return 1 ? Why do we not use res ?

There's no need to return `res`. Firstly, in the later versions of `waf`, `res` is not just a boolean anymore and secondly, `conf.fatal(msg)` prevents `waf` from continuing configuration...

> 
> Why does the library python script have to have #! /usr/bin/env python ?

It does not... I just put it always in my script to avoid using wrong version of python.. It's highly optional..

> 
> around line 69
> 
> Where is include_files defined ? Who has to fill it ? (I expect that it is the user, but it's not very clear in the tutorial)
> 

I have a comment just above that clearly (at least in my opinion) says that the user should specify a list of include files.

```py
# include_files is a list with the headers we expect to find
```

> around lines 68 and 96
> 
> Why do we define the res variable to True but never use it again ?

We do not need `res`. I forgot it there (copy paste). We should remove it..

> 
> around line 241
> 
> Why return 1 both when we failed and succeeded ?

Because we want to find `ROS` but it is not required. See above: it doesn't matter what we return, we have to use `conf.fatal(msg)` to prevent waf from continuing...

**Comment by dogoepp** [comment]
# Version number
Right now, the version number is 0.0 in Sphinx. To be updated ?

# `tutorials/advanced_example.rst`
## around line 7
In the figure, the last "t" of "Target" is trucated.

## around line 14
Why is "Squared exponential covariance function with automatic relevance detection" sorrounded by source code highlight backquotes ? Is there some documentation on this function ?

Before the list, it is written that we will "use the following", but we "optimize the hyperparameters"; not coherent

"Custom output statistics" needs clarification.

## around line 54
Is it "function evaluation" or "evaluation function" that we define ?

## around line 93
What is the role of ``dh_mat`` ? Why not directly using the values of ``rads`` ?

## around line 137
Should we link to the section of the documentation where state-based BO is explained ?

## around line 221
Maybe we can let the user know, what USB and CMAES are and that USB is used to optimise the acquisition function ? Or maybe the user is too clever to need this information ?

## around line 265
Is it normal that I can't guess what `kernel_squared_exp_ard`, `opt_rprop` and `opt_parallelrepeater` mean ?

## around line 297
> boptimizer.optimize(eval_func<Params>(), aggregator, false);

What is `false` doing ? Is it worth telling the reader about it ?

# `tutorials/statistics.rst`
## around line 75
> // [optional] we create a file to write
> //    you can use your own file but remember that this method is called
> //    at each iteration (you need to create it in the constructor)
> this->\_create\_log\_file(bo, "worst_observations.dat");

If manually creating a log file should be done in the constructor, why don't we do the same with ``create_log_file`` ? Even if this method is "safe", meaning that it will attempt to create the file each time, what is the benefit to doing it in this function instead of the constructor ?

> // [optional] we add a header to the file to make it easier to read later
> if (bo.total_iterations() == 0)
>     (\*this->\_log\_file) << "#iteration worst\_observation sample" << std::endl;

same question as above

# `guides/bo.rst`
## around line 4
> that is tailiored for very expensive objective function

What about

> that is tailored for very _time-consuming_ objective function

## around line 4
References to bibliographical elements seem to be buggy. The links for \[1\]\[5\] point to the ``limbo_concepts.rst`` page, although the bibliography at the bottom of the ``bo.rst`` page correctly points to the top of the page. This might be linked to the warnings shown during the build process.

See 3578c27 for a proposed solution. This proposal requires that a prefix be added when doing a citation. For instance,

    :cite:`brochu2010tutorial,Mockus2013`

becomes

    :cite:`a-brochu2010tutorial,a-Mockus2013`

The prefix `b-` would be used in ``limbo_concepts.rst``

## around line 31
Why is there no reference to $\chi_{0:t}$ in  
$P(f(\mathbf{x})|\mathbf{P}_{1:t},\mathbf{x}) = \mathcal{N}(\mu_{t}(\mathbf{x}), \sigma_{t}^2(\mathbf{x}))$ ?

## around line 45
> Our implementation of Bayesian optimization uses this Gaussian process model to search for the maximum of the objective function :math:`f(\mathbf{x})`, :math:`f(\mathbf{x})` being unknown.

Proposed alternatives:

- "... of the unknown objective function :math:`f(\mathbf{x})`."
- "... of the objective function :math:`f(\mathbf{x})`, which is unknown."

## around line 45
> Here we use the "upper confidence bound" acquisition function

Is it part of the normal (and documented) use case to define an other acquisition function ? If so, "Here" might be misleading.

## around line 45
> The model is then progressively refined after each observation.

Could we remove the "then".

## around line 58
What does the sentence bellow mean ? I don't see a link with the context above it.

> We use a log because it makes the optimization simpler and does not change the result.

## around line 74
what about

.. todo:: list the optimization algorithms

## Sections on hyper-parameters and kernel function
The two above-mentioned sections are not very well tuned together. The first one, on hyper-parameters talks about the kernel function that is only better explained later. It also shows computation with the squared exponential covariance function whereas the section on kernel function uses the matern kernel.

# `guides/general_concepts.rst`
Is this file used anywhere ? Sphinx says that it is included in no Table of Contents.

# `guides/limbo_concepts.rst`
## around line 31
I don't get what the following exerpt mecanism

> Different solutions exist to deal with missing data. The simplest way consists in redoing the evaluation. This may work, but only if the problem is not deterministic, otherwise the algorithm will be continuously redoing the same, not working, evaluation.

Actually, I finaly understood it, when reaching the end of the paragraph, because it was not clear that the first two paragraphs of this section are not specific to Bayesian Optimisation.

## around line 33
Maybe we can remove ", compatible with Bayesian Optimization," in the second sentence, since it adds very little information.

# `guides/framework.rst`
## around line 45
> - compile with: `./waf --exp my_experiment`

The compilation should be done from limbo's folder or the experiment's folder ?

# `guides/parameters.rst`
## around line 6
Would "Setting parameters in limbo" describe better the content of this guide than "Parameters" ?

**Comment by costashatz** [comment]
> In the figure, the last "t" of "Target" is trucated.

Not really.. See http://www.resibots.eu/limbo/_images/arm.svg

> Why is "Squared exponential covariance function with automatic relevance detection" sorrounded by source code highlight backquotes ? Is there some documentation on this function ?

I just wanted to emphasize which kernel we would use. We can just put in quotes or bold.

> Before the list, it is written that we will "use the following", but we "optimize the hyperparameters"; not coherent

You're right..

> "Custom output statistics" needs clarification.

We need to remove it. There's no custom stat..

> Is it "function evaluation" or "evaluation function" that we define ?

Evaluation function

> What is the role of dh_mat ? Why not directly using the values of rads ?

This is copy paste from Federico's code. We do not really care.

> Should we link to the section of the documentation where state-based BO is explained ?

Of course..

> Maybe we can let the user know, what USB and CMAES are and that USB is used to optimise the acquisition function ? Or maybe the user is too clever to need this information ?

It's UCB. For the user to reach the advanced example, we assume that he has already read the `Guides` and all the other `Tutorials`. So, he should be able to understand what UCB is. For CMAES, we should just say that it is an evolutionary algorithm that we use it for optimization.

> Is it normal that I can't guess what kernel_squared_exp_ard, opt_rprop and opt_parallelrepeater mean ?

You should be able to guess what `kernel_squared_exp_ard` means. `opt_rprop` and `opt_parallelrepeater` should be removed.

> What is false doing ? Is it worth telling the reader about it ?

`false` states that we do not want to reset the samples/observations in the `boptimizer`. You're right. We should say that to the user..

> that is tailiored for very expensive objective function
> What about
> 
> that is tailored for very time-consuming objective function

This is the same thing and the phrase "expensive objective function" is very often used in the literature.

> The compilation should be done from limbo's folder or the experiment's folder ?

limbo's folder will always have the expected behavior. Although, I believe that the same thing will happen if you call `waf` (which is located in limbo's folder) from whatever folder.

**Comment by dogoepp** [comment]
# `api.rst`
## around line 66
> +-- acqui: acquisition functions  
> |-- bayes_opt: bayesian optimizers

Why is there a `+` in front of "acqui" and a `|` for "bayes_opt" ?

This is the end of my review. I skipped most of the API documetation for which I trust you.

**Comment by dogoepp** [comment]
>> In the figure, the last "t" of "Target" is trucated.

>Not really.. See http://www.resibots.eu/limbo/_images/arm.svg

It is on my computer, see the attached picture.

targe

>> What is the role of dh_mat ? Why not directly using the values of rads ?

>This is copy paste from Federico's code. We do not really care.

Isn't a simpler example easier to read for a newbie? I can make the changes, but won't be sure they are right.

>> Maybe we can let the user know, what USB and CMAES are and that USB is used to optimise the acquisition function ? Or maybe the user is too clever to need this information ?

>It's UCB. For the user to reach the advanced example, we assume that he has already read the `Guides` and all the other `Tutorials`. So, he should be able to understand what UCB is. For CMAES, we should just say that it is an evolutionary algorithm that we use it for optimization.

I don't know of to phrase this. If you don't see either, let's skip this.

>> Is it normal that I can't guess what kernel_squared_exp_ard, opt_rprop and opt_parallelrepeater mean ?

> You should be able to guess what `kernel_squared_exp_ard` means. `opt_rprop` and `opt_parallelrepeater` should be removed.

I could use a little help for `kernel_squared_exp_ard`, specifically for `ard`. Do you mean that I should actually remove the two latter structs ?

>> What is `false` doing ? Is it worth telling the reader about it ?

>`false` states that we do not want to reset the samples/observations in the `boptimizer`. You're right. We should say that to the user..

Could you give it a try ? I'm no expert of limbo and might write nonsense.

----

What about the questions that you skipped ?

**Comment by costashatz** [comment]
> It is on my computer, see the attached picture.

It's not on mine! Some firefox/chrome weirdness probably..

> Isn't a simpler example easier to read for a newbie? I can make the changes, but won't be sure they are right.

I am not really sure. Let's leave it as it is for now.

> Do you mean that I should actually remove the two latter structs ?

Yes.

> I could use a little help for kernel_squared_exp_ard, specifically for ard

Squared Exponential Kernel with Automatic Relevance Detection 

> Could you give it a try ? I'm no expert of limbo and might write nonsense.

I will.

> What about the questions that you skipped ?


> around line 6
> 
> Would "Setting parameters in limbo" describe better the content of this guide than "Parameters" ?

Not really.

> around line 31
> 
> I don't get what the following exerpt mecanism
> 
> Different solutions exist to deal with missing data. The simplest way consists in redoing the evaluation. This may work, but only if the problem is not deterministic, otherwise the algorithm will be continuously redoing the same, not working, evaluation.
> Actually, I finaly understood it, when reaching the end of the paragraph, because it was not clear that the first two paragraphs of this section are not specific to Bayesian Optimisation.

I think that we will remove/replace "blacklists". So, we shouldn't really care for now..

> Why is there no reference to $\chi_{0:t}$ in
> 
> $P(f(\mathbf{x})|\mathbf{P}{1:t},\mathbf{x}) = \mathcal{N}(\mu{t}(\mathbf{x}), \sigma_{t}^2(\mathbf{x}))$ ?

There is. \chi_{0:t} is used to compute P_{1:t} and later for the kernels.

> Proposed alternatives:
> 
> "... of the unknown objective function :math:f(\mathbf{x})."
> "... of the objective function :math:f(\mathbf{x}), which is unknown."

The first one.

> Here we use the "upper confidence bound" acquisition function
> Is it part of the normal (and documented) use case to define an other acquisition function ? If so, "Here" might be misleading.

In my opinion, we should completely remove this sentence: *Here, we use the “Upper Confidence Bound” acquisition function (see the “information acquisition function” section below).*

> We use a log because it makes the optimization simpler and does not change the result.

When using logs, all the products become additions..

> guides/general_concepts.rst
> 
> Is this file used anywhere ? Sphinx says that it is included in no Table of Contents.

I do not know. @jbmouret wrote this..

**Comment by jbmouret** [comment]
guides/general_concepts.rst should probably be removed.

**Comment by costashatz** [comment]
> Could you give it a try ? I'm no expert of limbo and might write nonsense.
> I will.

@dogoepp We have first to merge #120, before doing this. I will wait for that...

**Comment by jbmouret** [comment]
Should we merge?

**Comment by costashatz** [comment]
> Should we merge?

We have to fix the conflicts. And add 1 line of comments. Will do.

@dogoepp did you finish with your changes?

**Comment by dogoepp** [comment]
let's make issues for each file so that it's easier to follow the many questions that are still not answered:

**Comment by dogoepp** [comment]
What do I do with the sequence diagram ?

**Comment by costashatz** [comment]
> What do I do with the sequence diagram ?

Didn't you have a newer version?

**Comment by jbmouret** [comment]
You put the new one!

**Comment by dogoepp** [comment]
@costashatz you can have a look at my latest commit for the new sequence diagram (API page). Share your remarks

**Comment by costashatz** [comment]
> @costashatz you can have a look at my latest commit for the new sequence diagram (API page). Share your remarks

I will. Please keep in mind that when you commit something that does not change compiled coded (e.g. only documentation), you can add `[ci skip]` to the commit message to avoid rerunning the ci compilations.. ;)

**Comment by dogoepp** [comment]
Yes, just after typing git push I realised that I had forgotten. 
Besides, I guessed this from one of your commits. Not written anywhere, 
in the wiki ? ;-) (probably useless to write it, won't be read).

**Comment by costashatz** [comment]
> @costashatz you can have a look at my latest commit for the new sequence diagram (API page). Share your remarks

I like it more than the previous one. Can you add some colors? :smile:

**Comment by dogoepp** [comment]
Sure, what colours would you like ?

**Comment by costashatz** [comment]
> Sure, what colours would you like ?

Like the previous one?

**Comment by dogoepp** [comment]
You mean for BOptimizer, init, etc ?

**Comment by costashatz** [comment]
> You mean for BOptimizer, init, etc ?

Whatever you like.. Just colorize it if you can.. :smile:

**Comment by dogoepp** [comment]
Here is the new proposal:

limbo_sequence_diagram

Anything more specific to suggest ?

**Comment by costashatz** [comment]
Excellent! I like it!

**Comment by dogoepp** [comment]
Thanks. Commiting.

**Comment by dogoepp** [comment]
Sorry, forgot again to put [ci skip] ...

**Comment by dogoepp** [comment]
Ready to **merge**

**Comment by dogoepp** [comment]
(after solving the conflict)

**Comment by costashatz** [comment]
> Sorry, forgot again to put [ci skip] ...

Thank god I am not doing the compilations manually. :tongue:

**Comment by costashatz** [comment]
> (after solving the conflict)

Which conflict?

**Comment by dogoepp** [comment]
There used to be some.

**Comment by costashatz** [comment]
> There used to be some.

Already solved! :smile: We will just wait for the tests to compile..

**Comment by costashatz** [comment]
I think we are **ready to merge...**

**Comment by dogoepp** [comment]
ready to **merge** too. OK JB ?

**Comment by jbmouret** [comment]
Ok

**Pull request merged**
