### PR TITLE
add the script used on the cluster to update the docs

### PR DESCRIPTION
**Pull request by jbmouret**

### CODE REVIEW

**Comment by costashatz** [comment]
Nice! **Merge**..

@jbmouret please note that if we do not change any code, but only docs (not compilation-related) add `[ci skip]` at the end to not build travis jobs..

**Comment by jbmouret** [comment]
I know. I just forgot (the script itself does the "[skip ci]" : it is the
same or should we change to [ci skip]?

-- JBM

**Comment by costashatz** [comment]
> I know. I just forgot (the script itself does the "[skip ci]" : it is the
> same or should we change to [ci skip]?

According to (this)[https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build], it is `[ci skip]`.

**Comment by costashatz** [comment]
**Merging..** @jbmouret do not forget to change the original script to have `[ci skip]`.

**Pull request merged**
