### PR TITLE
removed boost::shared_ptr and replaced them with std::shared_ptr

### PR DESCRIPTION
**Pull request by jbmouret**
There is no reason to use boost's shared_ptr since they have been included in the standard.

### CODE REVIEW

**Comment by costashatz** [comment]
Since we are removing `boost` related things. Maybe it's good to remove some more (like `boost::math`, `boost::swap` etc.). I will add some commits if you agree.

**Comment by jbmouret** [comment]
Sure, we should remove boost calls that are in C++-11. (But we need boost anyway for parameters).

**Comment by costashatz** [comment]
> But we need boost anyway for parameters

Yeap.

**Comment by costashatz** [comment]
I didn't find any clean way to replace these [lines](https://github.com/resibots/limbo/blob/remove_boost_shared_ptr/src/limbo/tools/macros.hpp#L71-L72). It can be done but with a loop. So, I am voting to leave this boost dependency, since we still have to use boost for parameters and fusion. Same thing goes for `boost::mpl` that can be replaced with some variadic templates etc, but it's too much work (and surely error prone). We can reconsider these changes when C++ provides parameters as boost does.

**Comment by costashatz** [comment]
Extensive tests pass. Should we merge?

**Comment by jbmouret** [comment]
@fedeallocati ?

**Comment by fedeallocati** [comment]
** Yeap, merge **

**Pull request merged**
