### PR TITLE
Gp nodim

### PR DESCRIPTION
**Pull request by Aneoshun**
Small bug fix:
Using the default constructor of GP imposes the dim_in and dim_out to be 1 for kernel and mean functions (because default constructors are called too) even if the dims are supposed to be automatically determined when computing the data. However, the new value of dim_in and dim_out are not propagated to kernel and mean functions, which results in an assert when computing multi-dimensional data with a gp built via the default constructor.

This branch improves the way the dims are automatically determined, removing the need of specifying the dims in the constructor.
I added a small test in test_gp.cpp to check that building multidimensional gp with the default constructor works well (this test raises an assert from Eigen with the current version of master). 

Moreover, the asserts regarding size of the data should be check every time, not only in the first call of "compute".

Minor improvement of .gitignore

### CODE REVIEW

**Comment by costashatz** [comment]
Seems **OK** and like a harmless change..

**Comment by fedeallocati** [comment]
**Looks good to me too**

**Comment by costashatz** [comment]
We should merge right?

**Comment by jbmouret** [comment]
OK for me. Let's merge.
-- JBM

**Pull request merged**
