### PR TITLE
Disabling clang-format for the macros file

### PR DESCRIPTION
**Pull request by fedeallocati**

### CODE REVIEW

**Comment by costashatz** [comment]
Did you run the clean tool on the code?

**Comment by fedeallocati** [comment]
Yes, and it doesn't change anything

**Comment by costashatz** [comment]
Weird. I am getting this diff:

```diff
diff --git a/src/limbo/macros.hpp b/src/limbo/macros.hpp
index 1d1bffa..419bcb4 100644
--- a/src/limbo/macros.hpp
+++ b/src/limbo/macros.hpp
@@ -60,5 +60,5 @@
     }
 
 #define BO_STRING(Name, Value) static constexpr const char* Name() { return Value; }
-// clang-format on
+         // clang-format on
 #endif
\ No newline at end of file
```

**Comment by fedeallocati** [comment]
Mmm, no idea, in my case it leaves the comment where it is

**Comment by costashatz** [comment]
Which version of clang-format do you have?

**Comment by fedeallocati** [comment]
Ubuntu clang-format version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)

**Comment by costashatz** [comment]
I am using exactly the same version. Anyhow, it works fine.

**Comment by fedeallocati** [comment]
So should I merge?

**Comment by costashatz** [comment]
Yeap! I will try to find something better, but until then.

**I approve**

**Comment by jbmouret** [comment]
**OK for me**
On 20 Oct 2015, at 13:39, Federico Allocati <notifications@github.com> wrote:

> So should I merge?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
Funny, now I run it on the gp_multi branch and it does what it did to you @costashatz , but in the add_macros branch it didn't do it. Perhaps line endings or something?

**Comment by costashatz** [comment]
I am not really sure. Play a bit with line endings and stuff, but it really shouldn't matter. Leave it as the clean tool produces it. It doesn't make any difference.

**Pull request merged**
