### PR TITLE
Added Aggregator Function to Init and Stats

### PR DESCRIPTION
**Pull request by fedeallocati**
I forgot to pass it to them when I made the state based bo branch

### CODE REVIEW

**Comment by jbmouret** [comment]
Why do we need it for the Stats?

**Comment by fedeallocati** [comment]
Typical example: The model models the position of the end effector -> the observations are 3d points. Then there is no way to ouput in the stats the actual performance of a sample, because it's not in the BO.

**Comment by jbmouret** [comment]
In that case, shouldn't we keep the actual performance of the samples in the BO? it sounds like something that could be saved in an attribute.

**Comment by fedeallocati** [comment]
It's still not useful when we want to do queries to the model, and then output the performance. A use case for this could be a Stat that prints the difference between the predicted performance and the actual obtained performance

**Comment by jbmouret** [comment]
Isn't the aggregator a member of BO by the way?

**Comment by fedeallocati** [comment]
No, it's the same as the State Function, it's received in the `optimize` method, because what we precisely want is to easily change it without changing the model or loosing the previous observations

**Comment by costashatz** [comment]
Thinking about it, it's good to have the `Aggregator` to the stats. Gives more functionality and I don't think it will cost anything.

**Comment by fedeallocati** [comment]
So what should we do with this? Merge? Make any change?

**Comment by costashatz** [comment]
Maybe we should add some specific tests for this functionality?

**Comment by costashatz** [comment]
> Maybe we should add some specific tests for this functionality?

What's the status on this one?

**Comment by fedeallocati** [comment]
There are no tests, if the code compiles then it's being called properly

**Comment by costashatz** [comment]
**OK for me** then.

**Comment by fedeallocati** [comment]
@jbmouret should I merge, or there is something else?

**Comment by jbmouret** [comment]
**OK for me** [I am still unconvinced but we need to move forward]

**Pull request merged**
