### PR TITLE
Changed main boptimizer loop according to issue #36

### PR DESCRIPTION
**Pull request by fedeallocati**
Simply changed the main loop. Tests pass and extensive tests compile.

### CODE REVIEW

**Comment by costashatz** [comment]
I think I see a problem with this formulation for the main loop:

```
init()

while samples.empty() or !stop:

    if !observations.empty()
        model.compute()
    end if

    new_sample = max arg (acquisition)
    new_obs = eval(new_sample)
    samples.add(new_sample)
    observations.add(new_obs)
    update_stats()
end while

if !observations.empty()
        model.compute()
end if
```

1) The numbers of iterations (actually computing something - `model.compute`) will be one less than the user has specified in the Params. This will happen as `observations` will be empty the first time we get into the loop. The only case where `observations` won't be empty is if we are using transfer learning. This adds another problem as the behavior of our stopping criteria won't be the same in every possible call of BOptimizer.

2) We won't be able to output the last computed data to stats. This will happen because the last `model.compute` doesn't have an `update_stats`.


I vote to keep the old loop and have 2 slots for the stats: one before compute and one after. As mentioned in #36 by @fedeallocati I think it's better to add the new slot as a different templated parameter to the BOptimizer.

**Comment by fedeallocati** [comment]
I don't see why the number of iterations would be 1 less. If the user specifies 50 iterations, we will have exactly 50 samples/observations, and after the loop, the model will be recomputed one last time to take into account this last iteration.

**Comment by fedeallocati** [comment]
To solve 2) I propose to keep this loop, and add a new template parameter called something like "end_stats", and they would be called only at the end of optimization (outside the loop, after the last model recomputing).

**Comment by costashatz** [comment]
> To solve 2) I propose to keep this loop, and add a new template parameter called something like "end_stats", and they would be called only at the end of optimization (outside the loop, after the last model recomputing).

I don't like it. It's not very intuitive. I don't see the reason why shouldn't we have something like that:

```
init()

if !observations.empty()
    model.compute()
end if

while samples.empty() or !stop:
    new_sample = max arg (acquisition)
    new_obs = eval(new_sample)
    samples.add(new_sample)
    observations.add(new_obs)
    update_before_stats()
    model.compute()
    update_after_stats()
end while
```

I find it clearer and more flexible without any real complication.

> I don't see why the number of iterations would be 1 less. If the user specifies 50 iterations, we will have exactly 50 samples/observations, and after the loop, the model will be recomputed one last time to take into account this last iteration.

You are right about this. My bad.

**Comment by fedeallocati** [comment]
The real question is: do we need the stats after the model re-computing?
Nevertheless, I like the idea of having a particular set of stats that are called only at the end. For example we could only need the final observation (the one that made the optimizer to stop), or the Hyperparameters at the end of the optimization, to see where they converged.

**Comment by costashatz** [comment]
> The real question is: do we need the stats after the model re-computing?

We may want to output something about our model. E.g. mean/kernel parameters, actual mean of model etc. I agree that most of the times won't be used, but it's something that we can add easily and maybe it'll be helpful. Even if we don't output stats after the model computing, I like the following more (which should be equivalent to the one you are suggesting):

```
init()

if !observations.empty()
    model.compute()
end if

while samples.empty() or !stop:
    new_sample = max arg (acquisition)
    new_obs = eval(new_sample)
    samples.add(new_sample)
    observations.add(new_obs)
    update_stats()
    model.compute()
end while
```

> Nevertheless, I like the idea of having a particular set of stats that are called only at the end. For example we could only need the final observation (the one that made the optimizer to stop), or the Hyperparameters at the end of the optimization, to see where they converged.

This is not a bad idea, but not to solve the other issue.

**Comment by fedeallocati** [comment]
> This is not a bad idea, but not to solve the other issue.

Actually, yes, because if you want the mean/kernel hyperparameters, you could have the corresponding stat in the usual stats (which will output with one iteration of "delay"), and set the same stat for the "final_stats", and then you will have also the last mean/kernel hyperparameters

**Comment by costashatz** [comment]
> which will output with one iteration of "delay"

I don't like this "delay" idea.

If you insist and as I cannot find one useful use-case at the moment for the after stats, I am suggesting the following:

```
init()

if !observations.empty()
    model.compute()
end if

while samples.empty() or !stop:
    new_sample = max arg (acquisition)
    new_obs = eval(new_sample)
    samples.add(new_sample)
    observations.add(new_obs)
    update_stats()
    model.compute()
end while

final_stat()
```

**Comment by fedeallocati** [comment]
Yeap, that's exactly what I was saying. I think this is totally consistent, because all stats will be updated with the used values to choose the sample, so you can see the hyperparameters that lead to the choice, the mu/sigma and acquisition, etc.

**Comment by fedeallocati** [comment]
Should be good now. The final_stat will be left to another PR, because I think it's not priority right now

**Comment by costashatz** [comment]
> The final_stat will be left to another PR, because I think it's not priority right now

I agree with this.

Extensive tests compiled. Everything seems fine!

**OK for me**

**Comment by fedeallocati** [comment]
@jbmouret thoughts on this? It's just instantiating the model before calling the initialization (some init function may assume that the instance of the model already exists, so it's dangerous to create it after), and calling the update of the model at the end of the loop

**Comment by jbmouret** [comment]
**OK for me**

**Pull request merged**
