### PR TITLE
Improvement in likelihood computation

### PR DESCRIPTION
**Pull request by costashatz**
Added the improvement in the likelihood computation @jbmouret talked about in #9 .

### CODE REVIEW

**Comment by fedeallocati** [comment]
Looks correct, although this will change with the functor approach to the likelihood optimization
**I approve**

**Comment by costashatz** [comment]
Of course it will change, but until we have it ready, this is better than before. ;)

**Comment by costashatz** [comment]
@jbmouret do you approve this change? On my experiments, it ran pretty well.

**Comment by jbmouret** [comment]
ok

**Pull request merged**
