### PR TITLE
Gp multi blacklist

### PR DESCRIPTION
**Pull request by fedeallocati**
Integrated blacklist functionality into GP and added a unit test to ensure that it behaves as expected.
Also added the utilization of blacklists in the simple bayesian optimizer.
Maybe they can be added to the multi objective optimization too.  @jbmouret opinion on that?

### CODE REVIEW

**Comment by costashatz** [comment]
It seems fine to me!

I will try to test them on my ITE experiments and let you know.

**Comment by costashatz** [comment]
I tested with my ITE experiments and everything seems to work nicely.

**I approve this PR.**

**Comment by costashatz** [comment]
I tested it with my ITE experiments and everything seems to work nicely.

**I approve this PR.**

**Comment by jbmouret** [comment]
_I approve this PR_.

**Pull request merged**
